version: '3.8'

services:
  backend:
    build: ./back
    ports:
      - 3001:3001
    volumes:
      - ./back:/app
      - /app/node_modules

  frontend:
    build: ./front
    ports:
      - 4200:4200
    volumes:
      - ./front:/app
      - /app/node_modules