### Testa a rota para sortear uma letra
POST http://localhost:3000/api/sorteiaLetra
Content-Type: application/json

###

### Testa a rota para inserir um jogador
POST http://localhost:3000/api/insere
Content-Type: application/json

{
  "name": "Erasmo",
  "nome": "Erasmo",
  "pais": "iEspanha",
  "objeto": "IElefante",
  "cor": "Azul",
  "animal": "Elefante",
  "letra": "E"
}

###

### Testa a rota para obter todos os jogadores
GET http://localhost:3000/api/users

###

### Testa a rota para obter um jogador por ID
GET http://localhost:3000/api/users/1

###

### Testa a rota para atualizar um jogador
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
  "name": "Erasmo",
  "nome": "Erasmo",
  "pais": "Espanha",
  "objeto": "Elefante",
  "cor": "Azul",
  "animal": "Elefante",
  "pontos": 10
}

###

### Testa a rota para deletar um jogador por ID
DELETE http://localhost:3000/api/users/1

###

### Testa a rota para deletar todos os jogadores
DELETE http://localhost:3000/api/users
